### ISSUE TITLE
WindowsにてDocker Buildができません。

### ISSUE THREAD

**Issue by takayasu** [ndl-lab/ndlocr_cli#1]
Windows 11 Pro 64bit にてDockerのビルドを実行しようとしています。
dockerbuild.sh　が動かないので、中身をみて、ファイルをダウンロードして配置しました。
そのうえで、
```
docker build -t ocr-cli-py37 -f docker\Dockerfile .
```
と実行したところ、以下のエラーが発生しました。

```
 > [ 3/18] RUN rm /etc/apt/sources.list.d/nvidia-ml.list:
#6 0.630 rm: cannot remove '/etc/apt/sources.list.d/nvidia-ml.list': No such file or directory
------
executor failed running [/bin/sh -c rm /etc/apt/sources.list.d/nvidia-ml.list]: exit code: 1
```

Ubuntuでテストされているとのことでしたが、Dockerのビルドであり、このエラーは
nvcr.io/nvidia/cuda:11.1.1-cudnn8-devel-ubuntu18.04
に依存している部分かもしれませんが、Dockerファイルのこの箇所を削除していいものか判断ができずIssueとしてあげさせていただきました。

**Comment by ndl-lab-staff** [comment]
ご報告ありがとうございました。

ご指摘いただいた箇所はNVIDIAが4月末にGPGキーを更新した際に、NVIDIA公式ベースイメージの更新が行われなかったため、ビルド不能になる事象に対応する目的で応急的に追加した箇所となります。
(参考)　
https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/

https://tech-blog.optim.co.jp/entry/2022/05/18/100000

Windows環境で起票内容の再現性を確認しましたところ、本日時点のベースイメージではGPGキーの更新が行われており、上記応急対応箇所に起因するエラーにより、逆にビルドエラーが発生することが判明しましたので、先ほど応急対応箇所の削除を行いました。

お手数ですが、最新のマスターブランチをご利用いただければ幸いです。

どうぞよろしくお願いいたします。

**Comment by takayasu** [comment]
ご対応ありがとうございます。Docker Buildが成功したのを確認できました。Closeとさせていただきます。
