### ISSUE TITLE
input画像などの設定に関する質問+readmeファイルの充実

### ISSUE THREAD

**Issue by junichiyamasaki** [ndl-lab/ndlocr_cli#13]
初めまして。docker初心者で、利用方法について初歩的な質問があります。

`readme`通りに進めていって、
`docker exec -i -t --user root ocr_cli_runner bash
`
までは済んだのですけど、この後手元の画像を

私の理解では`input_root`などはコンテナ内で
`mkdir input_root`
などとフォルダを別途作成する必要があると理解していますが、そうして作成したフォルダに手元の画像をコピーしようと
`docker cp C:\Users\username\Desktop\ocrtest.png ocr_cli_runner:/ocr_cli/input_root\ocrtest.png
`
としても、
`Error: No such container:path: ocr_cli_runner:~\ocr_cli\input_root
`
と出力されてしまいます。

このエラーをどうすれば良いのか、そもそもこのやり方をそちらが想定しているという理解で良いのか、というのが質問です。加えて、初心者の目で見たときに

- この理解に至るまでしばらくかかってしまったので、`readme`で省略されているこの作業を明記した方が親切かなと思いました。
- そもそも論としては、何かしらフォルダを初期設定でマウントしておいて、ホスト側で画像をGUIでコピーすれば良いようにしておいた方がわかりやすいのではと思いました。ファイルのホストコンテナ間の受け渡しをターミナルで行うのは一般ユーザーはあまり慣れていないかと思います。さらに言えば、何かしらのサンプル画像が`input_root`にあらかじめ置かれているとさらにわかりやすいと思います。

この2点、フィードバックさせていだければと思いました。お手数ですがご回答よろしくお願いいたします。

**Comment by ndl-lab-staff** [comment]
ご質問とフィードバックをいただきありがとうございました。

dockerに不慣れな方に不親切なREADMEであるというご意見につきましてはご指摘の通りと思います。ご不便をおかけして申し訳ございません。

今回ご質問いただいたようにコンテナの外部から画像ファイルを持ってくる場合、/root/ocr_cliがワーキングディレクトリになりますので、

`docker cp C:\Users\username\Desktop\ocrtest.png ocr_cli_runner:/root/ocr_cli/input_root/ocrtest.png
`
のようにしていただくと良いかと存じます。

ご意見いただいたホストマシンのディレクトリをデフォルトでマウントするようなREADMEの充実については、今年度改修中のNDLOCRの納品作業等を実施している都合、来年度早い時期に改修結果を反映する際に、改良を加えたいと考えています。

応急措置ではあるのですが、取り急ぎ、linux環境においてユーザがホストマシンの特定のディレクトリをマウントしたい際の参考情報を
https://github.com/ndl-lab/ndlocr_cli#5-%E5%87%A6%E7%90%86%E3%81%97%E3%81%9F%E3%81%84%E7%94%BB%E5%83%8F%E3%81%AE%E5%85%A5%E3%81%A3%E3%81%9F%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%88%E3%83%AA%E3%81%AE%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%88%E6%96%B9%E6%B3%95

に追記しておきました。windows環境においての同様の手順については検証後に追記させていただきますが、4月に入ってからになってしまうかもしれません。

どうぞよろしくお願いいたします。

**Comment by junichiyamasaki** [comment]
ご対応ありがとうございます！引き続き更新をフォローさせていただきます。
