### ISSUE TITLE
Index out of Rangeエラー

### ISSUE THREAD

**Issue by adachi1939** [ndl-lab/ndlocr_cli#28]
初めまして、
数ヶ月前、ColabでOCR作業を問題ないで行なっていましたが、最近、行なってみると`IndexError                                Traceback (most recent call last)`　`IndexError: list index out of range`というエラーメッセージが出ています。

![エラーのスクリンショット](https://i.imgur.com/sARY9iY.png)

よろしくお願いいたします。

**Comment by ndl-lab-staff** [comment]
エラーの再現性を確認しましたが、本リポジトリで提供しているNDLOCRに不具合は見受けられませんでしたので、colabノートブックの問題と考えられます。

ノートブック作成者の先生に不具合報告を行いましたので今しばらくお待ちください。
