### ISSUE TITLE
縦読みを指定することは可能でしょうか？

### ISSUE THREAD

**Issue by Keitaro-Ninomiya** [ndl-lab/ndlocr_cli#29]
はじめまして．
すべてのテキストが縦書きになっている資料の内容を本コードで摘出しようとしています．
テキストが縦書きなっているという情報をレイアウト抽出に反映させることは可能でしょうか？

手元にある資料にコードを走らせてみたところ，横書きと縦書きが混じった形でレイアウト検知が行われておりました．

最後にこのような試みをしてくださり誠にありがとうございます．

**Comment by ndl-lab-staff** [comment]
お返事が遅くなりまして失礼いたしました。
ご質問ありがとうございます。
お尋ねいただいた件ですが、現行のバージョンでは出力時にレイアウトの書き方向を指定する機能はありません。
[-x, --save_xmlオプション](https://github.com/ndl-lab/ndlocr_cli#-x---save_xml%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3)
で座標情報を含んだxmlを出力することができますので、こちらを加工して不要な書き方向を取り除いていただくとある程度改善されるかもしれません。
どうぞよろしくお願いいたします。
