### ISSUE TITLE
OCR結果が、行についてバラバラになる。

### ISSUE THREAD

**Issue by yoshikawa-jaea** [ndl-lab/ndlocr_cli#5]
txtに格納されるデータを見ると、各行ごとにはテキストデータに変換されているものの、行の順番がバラバラになります。
こちらの問題について心当たりはありますでしょうか?

**Comment by ndl-lab-staff** [comment]
現在公開しているNDLOCRは、読み順序の整序に対応していません。
したがって行の順番がバラバラになってしまっています。
今年度の改修で機能追加を行っていますので、2023年4月以降早々にアップデートして対応する見通しです。

なお、Google Colaboratoryバージョン(https://zenn.dev/nakamura196/articles/b6712981af3384)
は、試験的に読み順整序モジュールを追加していますので、テキストデータについて概ね正しい読み順で出力されるかと思います。

**Comment by yoshikawa-jaea** [comment]
了解いたしました。
アップデートを待ちたいと思います!
