### ISSUE TITLE
Colabのノートブックがバグっています

### ISSUE THREAD

**Issue by EtienneGagnon1** [ndl-lab/ndlocr_cli#7]
ColabでOCR作業を行う時に　`IndexError: list index out of range`というエラーメッセージが出ています。もともとノートブックに載っているURLでPDF入力しようとしても同じエラーがでますので、モデル側の問題かと思います。

![image](https://user-images.githubusercontent.com/42870103/220821028-eeef9e2e-55bd-4ad6-8ccb-c90acecafbd2.png)

**Comment by ndl-lab-staff** [comment]
ご報告誠にありがとうございます。

これまで同コミットに対して同様の不具合が確認できなかったことから、根本的な原因はGoogle colab側の仕様変更によるものと考えていますが、numpy及びscipyの要求バージョンを更新することで対処できました。
masterブランチに変更を取り込みましたので、再度お試し頂ければと思います。
どうぞよろしくお願いいたします。

**Comment by ndl-lab-staff** [comment]
対応から1週間経過しましたので本件はクローズさせていただきます。
また何かございましたら再オープンして頂ければと存じます。
どうぞよろしくお願いいたします。

**Comment by EtienneGagnon1** [comment]
対処したことを確認しました。ありがとうございました。
